### ISSUE TITLE
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by ghyujkilop** [minis-patchers/SynWeaponKeywords#11] opened 2022-06-07 09:20 UTC
Compiling
Extra data folder already exists. Leaving as is: "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords"
("C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords"): "dotnet" "build \"SynWeapType.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "17a08777de29e47361b1c0021f655a2cead6ad51"
Running
(""): "dotnet" "run --project \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\SynWeapType.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder \"D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords\" --DefaultDataFolderPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Data\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp\" --PatcherName SynWeaponKeywords --SourcePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - WeaponSpeedEffectsFix\Synthesis.esp\""
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at WeaponKeywords.Program.ConvertJson() in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Program.cs:line 40
   at WeaponKeywords.Program.Main(String[] args) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Program.cs:line 30
   at WeaponKeywords.Program.<Main>(String[] args)
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 57
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 58
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 84

**Comment by Minizbot2012** [comment] 2022-06-07 19:24
Send me your Data/SynWeaponKeywords/database.json as there is a value in there that under no circumstances should be touched

**Comment by ghyujkilop** [comment] 2022-06-08 00:28
Sweet, just updated it to the most recent version and got this:
`Compiling
Extra data folder already exists. Leaving as is: "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords"
("C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords"): "dotnet" "build \"SynWeapType.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "696ca2c013a34aef26d8f15afa249f7b1bf13324"
Running
(""): "dotnet" "run --project \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\SynWeapType.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder \"D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords\" --DefaultDataFolderPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Data\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp\" --PatcherName SynWeaponKeywords --SourcePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - WeaponSpeedEffectsFix\Synthesis.esp\""
Mutagen version: 0.36.3
Mutagen sha: fc2d89802dd42fe2558e6c754b35a130d7f2c09f
Synthesis version: 0.22.1
Synthesis sha: 820cdd4f57945993117de9613b154f002b930eeb
run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords" --DefaultDataFolderPath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Data" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\Plugins.txt" --LoadOrderIncludesCreationClub --OutputPath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp" --PatcherName SynWeaponKeywords --SourcePath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - WeaponSpeedEffectsFix\Synthesis.esp"
Checking runnability
Checking runnability complete
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
Reading settings: D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords\database.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponKeywords.Program.<>c__DisplayClass6_3.<RunPatch>b__7(KeyValuePair`2 kv) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Program.cs:line 96
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at WeaponKeywords.Program.RunPatch(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\ldt33kym.nun\Runner\SynWeaponKeywords\Program.cs:line 0
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 57
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 58
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 84`

json: https://ufile.io/2khxkhmg

**Comment by Minizbot2012** [comment] 2022-06-08 02:58
I'm gonna note that you are running a massively outdated JSON DB (I'm gonna be working on that in the future). The error was caused by the outdated DB and the conversion code not handling it (As I only handled what I had published for a short time before). But this should be fixed now with Schema 2, let me know if its still broken after you update and run.

**Comment by ghyujkilop** [comment] 2022-06-08 03:54
All fixed on my end man, you can consider this closed! Do I need to do anything on my end to update my JSON DB? I'm not sure how to do that. But no errors anymore!

**Comment by Minizbot2012** [comment] 2022-06-08 04:12
All you'd need to do is delete Data/SynWeaponKeywords/ (the folder, starting where the synth exe is), but again I am working on some new things to handle this :)

**Closed as completed by Minizbot2012** 2022-06-08 04:12 UTC
